### ISSUE TITLE
Design changes

### ISSUE THREAD

**Issue by tavi004** [Inevio/GoogleCalendar#10]
# Sidebar

The favicon should be this icons: ![logo_calendar_128px](https://user-images.githubusercontent.com/3248361/34561820-14a95a5c-f14c-11e7-817b-a68d9117c86d.png)![logo_calendar_128px 2x](https://user-images.githubusercontent.com/3248361/34561821-14be379c-f14c-11e7-9af4-a44d98f7d1c7.png)

![image](https://user-images.githubusercontent.com/3248361/34561567-f58461d6-f14a-11e7-8102-faec0d2fce57.png)
![image](https://user-images.githubusercontent.com/3248361/34561572-fb3ca2e6-f14a-11e7-9edc-6585549e2fd6.png)
# Tools

For the arrows use this sprites: ![arrow-sprite](https://user-images.githubusercontent.com/3248361/34561863-3834d24e-f14c-11e7-9189-35d7d5359c8d.png)![arrow-sprite 2x](https://user-images.githubusercontent.com/3248361/34561864-384a15b4-f14c-11e7-9868-b067c4af774b.png)

![image](https://user-images.githubusercontent.com/3248361/34561586-04023238-f14b-11e7-99a4-59a9b1a7edcb.png)
![image](https://user-images.githubusercontent.com/3248361/34561594-0b41d0a8-f14b-11e7-8068-3e29db831cc9.png)

# Day view
When you are in the day view, on Today, it shouldn't be colored but white
To differentiate the current day than others, the text above should be in bold when current and normal when is any other day

![image](https://user-images.githubusercontent.com/3248361/34562462-d40ab07e-f14e-11e7-98de-2f9e593a52a0.png)

# Week view

On the current day the color it should be #f5f5f5 not that yellow
The days they shouldn't be in bold except the current day.
![image](https://user-images.githubusercontent.com/3248361/34562633-8c4f3c04-f14f-11e7-861b-8bb6921fd1e3.png)

# Month

On the current day the color it should be #f5f5f5 not that yellow
The days they shouldn't be in bold except the number of the current day
Same as the others, the days should go up 8px
![image](https://user-images.githubusercontent.com/3248361/34562633-8c4f3c04-f14f-11e7-861b-8bb6921fd1e3.png)

**Comment by umair-brainx** [comment]
I will look into this

**Comment by umair-brainx** [comment]
Made the all design changes listed above. Kindly have a look.

**Comment by tavi004** [comment]
You forgot to do the Avatar part, it should be round 31x31px and the name centred, like in the image above. 
And the sidebar should have scroll.
![image](https://user-images.githubusercontent.com/3248361/34989053-4a9996a8-fac1-11e7-8aaa-b6fe4397c35f.png)

**Comment by umair-brainx** [comment]
I have made the Avatar change. Have a look now. as for sidebar I have already answered that in separate issue #12

**Comment by tavi004** [comment]
The photo of the avatar seems streched, could you preserve the proportions of the image?

And the content should go up 11px 
![image](https://user-images.githubusercontent.com/3248361/34994590-58f2949e-fad4-11e7-877f-7fd2aa4cb835.png)

**Comment by umair-brainx** [comment]
I have made these two changes. Have a look now.

**Comment by tavi004** [comment]
Looks good, one more thing the placeholder is not centred, move it up 1px 
![image](https://user-images.githubusercontent.com/3248361/35040760-a3d78268-fb82-11e7-874b-5fda2ef6d373.png)

**Comment by umair-brainx** [comment]
The placeholder is in its default vertically position.

**Comment by jorge9200** [comment]
ok it doesnt matter, lets close this issue
