### ISSUE TITLE
Calendar in wrong category

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#11]
In native app, super calendar is on "my calendars" category:
![image](https://user-images.githubusercontent.com/8724844/34830406-076f723e-f6e4-11e7-990e-531ee23440db.png)

In horbito app, super calendar is on "other calendars" category:
![image](https://user-images.githubusercontent.com/8724844/34830422-140511f2-f6e4-11e7-833e-8c7ac7f45169.png)

**Comment by umair-brainx** [comment]
![screen shot 2018-01-11 at 10 41 49 pm](https://user-images.githubusercontent.com/26704318/34838681-d510be28-f720-11e7-8559-db7130be5cf8.png)
I am using the isPrimary filed of the calendar entry. @icastillejogomez let me know should I use some other parameter to differentiate b/w my calendars and other calendars?

**Comment by jorge9200** [comment]
Hi @umair-brainx ,

Our api is simply a bind of the Google calendar api. Therefore, we would appreciate if you could try to solve the problems first by looking in the google documentation. There you can test the api with any account.

https://developers.google.com/google-apps/calendar/v3/reference/  

If google does not have a solution to this problem then we can not do anything about it :(

  If you find a solution on google that we are not offering you, we will improve or fix our API in order to offer it to you :)

So please, from now on, try to look at the google documentation to tell us what you need, because that way we can be much quicker fixing the errors.

**Comment by jorge9200** [comment]
Probably gmail list as "my calendars" the ones I create and "other calendars" the ones I didn't create. I think this because issue #3 last comment. But please try first to research it on google calendar documentation.

**Comment by umair-brainx** [comment]
I have changed the logic. Have a look know.

**Comment by icastillejogomez** [comment]
I can see the login view yet if I already have an account associated for a few seconds, but I I can see it. Fix this please. Thank you so much.

**Comment by umair-brainx** [comment]
The time it shows is while listAccounts fetch data. I don't see any functionality in horbito to stop screen render until listAccounts return. If there is any functionality let me know I will use that.

**Comment by jorge9200** [comment]
Inevio meetings calendar still on "my calendars" when it is not. But is really better, what atribute are you checking now for distinguish between mine and other calendars (I want to check it on google calendar api to see whats happening with inevio meetings one)

NATIVE
![image](https://user-images.githubusercontent.com/8724844/34934667-963a184e-f9db-11e7-98be-8c75c4a145bd.png)

HORBITO
![image](https://user-images.githubusercontent.com/8724844/34934675-a04693d0-f9db-11e7-9493-318798c2af5c.png)

**Comment by umair-brainx** [comment]
I am checking that if you have owner or writer access then it will be considered as My calendars.

**Comment by umair-brainx** [comment]
let me know on what parameters do you want me to differentiate.

**Comment by jorge9200** [comment]
Yes now I see, I think gcalendar is classifying as "my calendars" only the ones with owner. "writer and reader" goes to "other calendars"

**Comment by jorge9200** [comment]
set "my calendars" only to owner ones

**Comment by umair-brainx** [comment]
No. I don't think so. Well I am putting a check if its owner **or** writer then it will be considered as my calendar otherwise it will go to Other calendar. let me know if you want something different.

**Comment by umair-brainx** [comment]
I have made the check to consider calendar as "my" only if it has owner access.

**Comment by jorge9200** [comment]
done!
