### ISSUE TITLE
Add scroll to sidebar menus

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#12]
Can you re-organice your code like this? It's a really fast change (I made it on chrome dev tools)

1. Create a new div with class wz-scroll
2. Insert into it the 3 sidebar menus (miniCalendarSection, otherCalendarsSection, myCalendarsSection)
3. Add height: calc(100% - 112px); to this new parent div

![image](https://user-images.githubusercontent.com/8724844/34935174-4341da44-f9dd-11e7-9359-f35753d80076.png)

![image](https://user-images.githubusercontent.com/8724844/34935251-82d4308a-f9dd-11e7-82b2-18cd9cc672a6.png)

**Comment by umair-brainx** [comment]
I can't do any extra enhancement until we close milestone 3 no matter how small it is.

**Comment by jorge9200** [comment]
ok, no problem I'll keep this on my side

**Comment by umair-brainx** [comment]
Fixed.
