### ISSUE TITLE
Implement the "added account" event.

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/GoogleCalendar#13]
When OAuth process is complete, "added-account" event is send to the app. The way to implement is the same like the others events. 

`api.integration.gcalendar.on('added-account', callback)`

**Comment by umair-brainx** [comment]
Hi @jorge9200 ,
Can you explain it bit more I have implemented the api call 
![screen shot 2018-03-05 at 12 53 39 pm](https://user-images.githubusercontent.com/26704318/36963281-688e3ec4-2074-11e8-8a16-d46fdbaccd2e.png)

but what should be done in the callback?

**Comment by jorge9200** [comment]
this event is triggered when a account is added. You have to use it, at first init, when the user add an account you need it to know when its recieved and accepted.

**Comment by umair-brainx** [comment]
I have implemented the added-account method but not able to test it. as my account is already added and removeAccount method is not working.

**Comment by jorge9200** [comment]
@javiergarmon working in that

**Comment by jorge9200** [comment]
it should be working now

**Comment by umair-brainx** [comment]
Fixed. Kindly have a look and update me.
