### ISSUE TITLE
Create new event Time format is wrong

### ISSUE THREAD

**Issue by tavi004** [Inevio/GoogleCalendar#16]
In the design the Time has a date and hour format, not just a simple input. And when you click on the date should appear a mini-calendar that lets you choose the date.  
![image](https://user-images.githubusercontent.com/3248361/35620596-e3c95ed2-0681-11e8-82ec-75bd908eb5aa.png)

Implemented: this shouldn't be done.
![image](https://user-images.githubusercontent.com/3248361/35620623-fd186ff4-0681-11e8-92dd-e3a8caaa3bfa.png)

**Comment by tavi004** [comment]
I've seen that you've integrated the minicalendar. Could you trigger the calendar once you click on the whole input not just the arrow down icon. thanks!

**Comment by umair-brainx** [comment]
No. We can't do that.
