### ISSUE TITLE
Create new calendar errors

### ISSUE THREAD

**Issue by tavi004** [Inevio/GoogleCalendar#17]
Here I attach you some videos of the process. On the first video I create the calendar and I only click ONCE and it creates it but it takes a lot and it doesn't give you any feedback of what is doing. So here comes the 2nd and 3rd video, when I click the create calendar button I click it multiple times because I am not sure if is doing anything and it gives me that bug, of the popups and it creates the calendar multiple times.

![image](https://user-images.githubusercontent.com/3248361/35622752-3e393bb0-0689-11e8-8ac2-969129e1d89d.png)
[gcalendar.zip](https://github.com/Inevio/GoogleCalendar/files/1681630/gcalendar.zip)
[gcalendar2.zip](https://github.com/Inevio/GoogleCalendar/files/1681632/gcalendar2.zip)
[gcalendar3.zip](https://github.com/Inevio/GoogleCalendar/files/1681634/gcalendar3.zip)

**Comment by umair-brainx** [comment]
Fixed.
I have added a simple loading overlay.
