### ISSUE TITLE
Create event design changes

### ISSUE THREAD

**Issue by tavi004** [Inevio/GoogleCalendar#18]
- [ ] The red arrows should be font-weight: 900 and the blue ones Bold. ![image](https://user-images.githubusercontent.com/3248361/35627113-318ee086-0698-11e8-8f60-275ede7740ca.png)
-----------------------------
- [ ] Double the padding of the inputs to 14px on all the inputs: ![image](https://user-images.githubusercontent.com/3248361/35627173-669a6dcc-0698-11e8-91df-9788f28bf85b.png)
-----------------------------
- [ ] This should be all in one line not 2: ![image](https://user-images.githubusercontent.com/3248361/35627370-fee07626-0698-11e8-83fb-483e6ac43587.png)![image](https://user-images.githubusercontent.com/3248361/35627371-02b9cbee-0699-11e8-8e85-0fefe7a9306a.png)
-----------------------------
- [ ] Use this icon for the select button: ![select](https://user-images.githubusercontent.com/3248361/35627875-90b650b0-069a-11e8-9a3b-723daf5e97ee.png)![select 2x](https://user-images.githubusercontent.com/3248361/35627876-90d05212-069a-11e8-852a-325dcdebdc33.png)                ![image](https://user-images.githubusercontent.com/3248361/35627886-98c823b4-069a-11e8-94d7-aca01ecf4c59.png)
-----------------------------
- [ ] Space betwin elements: ![image](https://user-images.githubusercontent.com/3248361/35628393-0eddb9c8-069c-11e8-8ef8-adb6f1ecb711.png)

**Comment by umair-brainx** [comment]
1-Fixed the bold and bolder part
2-Fixed Padding Left of inputs
3-Fixed made it in single line.
5-Fixed the spaces.

4-We can't change, these dropdown icons are by default icons of HTML5.

**Comment by tavi004** [comment]
There shouldn't be this horizontal scroll and that gray separation 
![image](https://user-images.githubusercontent.com/3248361/35669543-b41ba604-0735-11e8-88f0-83fda69f1a75.png)

**Comment by tavi004** [comment]
The inputs should be aligned. There is no need for the date input to be that large. And the separation is not the one I provided, should be 12 not 17px

![image](https://user-images.githubusercontent.com/3248361/35669754-7190b1f2-0736-11e8-8372-66001bbb394f.png)


In the psd: 
![image](https://user-images.githubusercontent.com/3248361/35669603-f2c03208-0735-11e8-8b0d-59aad38621ed.png)

**Comment by umair-brainx** [comment]
1-Removed the horizontal scroll and that gray separation.
2-Made the width of date and time according to your Psd. Although previously I intentionally made it larger for complete date visibility. 
3-Fixed the 17px margin issue.

**Comment by tavi004** [comment]
I'm going to close this issue and create 2 new issues, one with enhancements for Milestone 6 and one with what is left of this one like the scroll and the date input
