### ISSUE TITLE
There is no way to edit a calendar

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#19]
We need a way to edit a calendar. We suggest this one (the easiest):

```
$('. calListLabel').on('contextmenu', function(){
  var contextMenu = api.menu()
  menu.addOption( "Edit calendar", launchEditCalendarView() )
  menu.addOption( "Remove calendar", removeCalendar() )
  menu.render()
});
```

This will trigger on right click on calendar objects.

**Comment by umair-brainx** [comment]
I have implemented the editing of calendar but when implementing the editing of user permission of calendar I am receiving two extra rows in method aclList
![screen shot 2018-03-06 at 3 03 37 pm](https://user-images.githubusercontent.com/26704318/37026483-5d078da8-2150-11e8-8220-4db764586fe3.png)

**Comment by jorge9200** [comment]
show all ACL exccept the one with ```"etag":"\"00000000000000000000\""```

**Comment by umair-brainx** [comment]
Google APIs don't allow to edit ACL with user own email. so I have added one more check so no we are allowing editing of user permissions except the one with "etag":"\"00000000000000000000\"" and except the one with currently logged in user email.

**Comment by umair-brainx** [comment]
@jorge9200  Edit Calendar Functionality along with user permissions has been completed. Kindly have a look and update me.
