### ISSUE TITLE
There is no app title 

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#2]
![image](https://user-images.githubusercontent.com/8724844/33062934-20711e06-cea1-11e7-97ab-765eb660743b.png)

**Comment by umair-brainx** [comment]
App title is there kindly have a look now

**Comment by umair-brainx** [comment]
![screen shot 2018-01-10 at 12 48 40 pm](https://user-images.githubusercontent.com/26704318/34761222-ace1ee76-f604-11e7-8a2f-0c30e191333b.png)

**Comment by jorge9200** [comment]
Is only happening on spanish mode, theres have to be a syntax error on es.json

**Comment by umair-brainx** [comment]
fixed. kindly have a look now

**Comment by umair-brainx** [comment]
![screen shot 2018-01-10 at 2 40 35 pm](https://user-images.githubusercontent.com/26704318/34765813-5020109a-f614-11e7-8206-74beeab66f27.png)

**Comment by jorge9200** [comment]
It's fixed! please assign me the next issue you complete, the notifications here in github are a little bit dumb, is the only way I can quickly see what is on my side.
