### ISSUE TITLE
Change first day of week functionality

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#26]

**Comment by umair-brainx** [comment]
@jorge9200 What is the new first day of week you want?

**Comment by umair-brainx** [comment]
New Design:
![image-1](https://user-images.githubusercontent.com/26704318/37332743-614e9ae0-26c9-11e8-9515-2aba32de1970.png)

**Comment by umair-brainx** [comment]
I have implemented the Function for this issue.
![screen shot 2018-03-13 at 3 20 19 pm](https://user-images.githubusercontent.com/26704318/37336083-1a8e4142-26d2-11e8-984e-1beac766e2c6.png)

**Comment by jorge9200** [comment]
perfect

**Comment by jorge9200** [comment]
Moved to Milestone 7 Remaining:

- [ ] Include change start day UI button linked to previous function made

**Comment by umair-brainx** [comment]
Fixed. Kindly have a look and update me accordingly.
