### ISSUE TITLE
It takes to long to create new calendar

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#27]

**Comment by umair-brainx** [comment]
@jorge9200 you will remember that here we are calling two APIs one for create new calendar that returns the id of newly created calendar but missing some of its info then we call get calendar API with the id to get fill details of calendar.

Instead the create new calendar API should return the full details of newly created calendar. Once you guys fixed this from APIs let me know I will make adjustments on my end.

**Comment by jorge9200** [comment]
ok, perfect
