### ISSUE TITLE
Changes event popup

### ISSUE THREAD

**Issue by tavi004** [Inevio/GoogleCalendar#28]
The Card should have this border and shadow, always on the same direction, not like right now that if the card is down the shadow is down and if the card is up the shadow is up.

  border-style: solid;
  border-width: 1px;
  opacity: 0.1;
  box-shadow: 0px 2px 4px 0px rgba(0, 1, 1, 0.1);

**Comment by umair-brainx** [comment]
Hi @tavi004 ,
I am using the popup-base.png image from PSD provided by you as background of popup card that has shadow built in. In case of upside down I just rotate the image. so can you send me a upside down image of this with correct shadow. Here is the current image I am using.
![popup-base](https://user-images.githubusercontent.com/26704318/36209062-80752320-11bc-11e8-922a-d140734f487c.png)

**Comment by tavi004** [comment]
![popup_base_reversed](https://user-images.githubusercontent.com/3248361/36209554-5032b616-119c-11e8-8377-cff8c2ac1b74.png)
![popup_base](https://user-images.githubusercontent.com/3248361/36209556-506af8d2-119c-11e8-9886-5bc7c9bf3c5d.png)

**Comment by umair-brainx** [comment]
Fixed. Kindly have a look.
