### ISSUE TITLE
Is not showing all the events

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#3]
Some events that I have and I can see on native google calendar app I can't see them on horbito gcalendar app:

Native app:
![image](https://user-images.githubusercontent.com/8724844/33063093-b62b1b54-cea1-11e7-86cf-f2c9ea58f3fa.png)

horbito app:
![image](https://user-images.githubusercontent.com/8724844/33063102-c079bbb0-cea1-11e7-9f6e-f27eb2e89ddd.png)

**Comment by jorge9200** [comment]
Other example:

horbito:
![image](https://user-images.githubusercontent.com/8724844/34489030-003ab5a6-efdb-11e7-8da0-6c25718e5a10.png)


native:
![image](https://user-images.githubusercontent.com/8724844/34489010-fabcb340-efda-11e7-8755-e39295a34ce3.png)

**Comment by umair-brainx** [comment]
For me its showing all events. I have just double checked for all months of 2018 and its showing me exact same. Can you try again on your side? And if its not showing all can you let me know what type of events is not being shown.

**Comment by jorge9200** [comment]
It is only happening with "Other calendars"

Look on native app, I have gmail calendar events (my calendar) and inevio meetings events (other calendars)

![image](https://user-images.githubusercontent.com/8724844/34764388-ae091f4c-f5ee-11e7-9701-8eaf0e751060.png)


On horbito app is only showing my calendar events not inevio meetings ones.

![image](https://user-images.githubusercontent.com/8724844/34764467-eef16c9e-f5ee-11e7-8da0-00e93499ce02.png)

Maybe the api is not returning other calendar events, check it and pass it @icastillejogomez in that case to investigate how to solve that.

**Comment by umair-brainx** [comment]
For me events from other calendars are being shown like in image 'Holidays in Pakistan' is an others calendar and its events Kashmir Day or New Year Eve are being shown

**Comment by umair-brainx** [comment]
![screen shot 2018-01-11 at 10 04 26 pm](https://user-images.githubusercontent.com/26704318/34837088-9a663b72-f71b-11e7-809a-2ac2348f1e03.png)

**Comment by umair-brainx** [comment]
Can you debug this with @icastillejogomez and let me know if there is something wrong on my side

**Comment by jorge9200** [comment]
@umair-brainx  "Holidays in Pakistan" and "umairasharaf.me@gmail.com" are calendars that you created. Horbito app shows "Holidays in Pakistan" as other calendars because issue #11 

Thats why you can see both calendar events, the problem is with REAL other calendars (My case of Inevio meetings) a calendar which I didn't create.

Please, try to reserach on google calendar doc how can you list events from calendar you didn't create. 
https://developers.google.com/google-apps/calendar/v3/reference/

**Comment by umair-brainx** [comment]
@jorge9200 You are totally wrong here.
First of all 'Holidays in Pakistan' is not created by me. and secondly see here. Its listed in others calendar category on native app so it does in our app.
![screen shot 2018-01-15 at 9 53 55 am](https://user-images.githubusercontent.com/26704318/34927735-3b43fa32-f9da-11e7-99eb-62fc992d0c51.png)

To debug the issue with your account there can be two possible options:
1-You can debug this with @icastillejogomez and figure out where is problem
2-We can jump over call through team viewer and I can debug on your PC.

let me know whatever suit you best.

**Comment by jorge9200** [comment]
Hello @umair-brainx I just find the problem just looking on Google Calendar API documentation. The problem with my calendar "Inevio Meetings" is that have a lot of events in it, and gmail pass with the callback a "nextPageToken".

![image 2018-01-16 13 22 29](https://user-images.githubusercontent.com/8724844/34988804-4eeb3398-fac0-11e7-8177-11287aa7609b.jpg)

You have to re-call listEvents method with this token on the params

![image](https://user-images.githubusercontent.com/8724844/34988853-8181a03a-fac0-11e7-89ff-b91f6ad8331f.png)
![image](https://user-images.githubusercontent.com/8724844/34988858-86b6d534-fac0-11e7-92bc-3b8c80f95b18.png)

There is no problem in @icastillejogomez api

**Comment by umair-brainx** [comment]
I have added the handling of nextPageToken. Kindly test it on your side and let me know.

**Comment by jorge9200** [comment]
fixed
