### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by tavi004** [Inevio/GoogleCalendar#32]
The arrow icons are not showing correctly ![image](https://user-images.githubusercontent.com/3248361/37665378-62fd726e-2c5d-11e8-88c6-b74b136d863f.png)

This icon on the design is 14x14px![image](https://user-images.githubusercontent.com/3248361/37665521-c11dd6f4-2c5d-11e8-8d72-bcda3c199140.png)
![refresh-icon](https://user-images.githubusercontent.com/3248361/37665543-cc087632-2c5d-11e8-8fbc-c4d1c72edbf8.png)
![refresh-icon 2x](https://user-images.githubusercontent.com/3248361/37665544-cc227e74-2c5d-11e8-8a9a-64bc7b7bd7ad.png)

**Comment by umair-brainx** [comment]
Fixed. I have made the icons 14 x 14.

![screen shot 2018-03-21 at 10 17 25 pm](https://user-images.githubusercontent.com/26704318/37725841-b08f6aca-2d55-11e8-8958-d3458387cf94.png)
