### ISSUE TITLE
Event without date

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#35]
You can create a new event without date (it will automatically set to 00:00) but then you can not click on it:

![image](https://user-images.githubusercontent.com/8724844/37782712-df4fccf8-2df3-11e8-86d8-c1cb6f31fdae.png)

**Comment by umair-brainx** [comment]
kindly explain it more how you are able to create new event without date? by removing date using backspace.
For me its showing error that invalid date.

**Comment by jorge9200** [comment]
click on a day > uncheck all day checkbox > set a name for the event > save

then try to click or interact with this event

**Comment by umair-brainx** [comment]
Fixed. I have added the validation that user has to select valid start and end time
