### ISSUE TITLE
Impossible date range

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#36]
![image](https://user-images.githubusercontent.com/8724844/37782787-1713caea-2df4-11e8-9d29-7c9f97cadfea.png)

When you set a impossible date range it says:

![image](https://user-images.githubusercontent.com/8724844/37782807-23f748fe-2df4-11e8-96cb-3a18939d4c84.png)

It have to inform you better about what is happening, something like "The date range selected is not allowed"

**Comment by umair-brainx** [comment]
this is the message I am getting from API. if you want another message you can customize it from API.
