### ISSUE TITLE
When you deactivate all calendars, some events still visible 

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#41]
Try yourself adding google public calendars

![image](https://user-images.githubusercontent.com/8724844/37911202-acf52d7e-310f-11e8-8516-64aee8d1665d.png)

**Comment by umair-brainx** [comment]
I have tried and for me its working perfect
![screen shot 2018-03-26 at 10 20 12 pm](https://user-images.githubusercontent.com/26704318/37921678-f1434130-3143-11e8-9bf1-bf2815a9331e.png)

**Comment by jorge9200** [comment]
Now is working right for me, I'll try to replicate again and tell you
