### ISSUE TITLE
The app doesn't save the account you entered

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#5]
Every time you open the app you have to login with your account, you can ask our API the already logged accounts and listed directly.

**Comment by umair-brainx** [comment]
This needs to be fixed from auth process by your guy who is working on APIs

**Comment by icastillejogomez** [comment]
![image](https://user-images.githubusercontent.com/16567802/34827824-bed9ee12-f6db-11e7-95a3-ae3979b3fe84.png)

you are not calling listAccounts function.

**Comment by jorge9200** [comment]
yes, @umair-brainx you have to listAccounts and auto-login in the one the user had entered

**Comment by jorge9200** [comment]
only addAccount where there is no accounts on listaccounts

**Comment by umair-brainx** [comment]
Fixed. Kindly have a look.

**Comment by icastillejogomez** [comment]
video: http://wz.io/f/A6BCggEV

If an user already have saved the account, GCalendar must to show directly his calendar and not the login view.

If an user don't have any account saved, GCalendadr must to show the login view and save the account after.

Please fix it and thank you so much :)

**Comment by umair-brainx** [comment]
I have made it to check at start of login view if user has already an account it will redirect to Calendar view otherwise It will stay at login view. Kindly have a look.

**Comment by icastillejogomez** [comment]
I can see the login view yet if I already have an account associated for a few seconds, but I I can see it. Fix this please. Thank you so much.

**Comment by umair-brainx** [comment]
The time it shows is while listAccounts fetch data. I don't see any functionality in horbito to stop screen render until listAccounts return. If there is any functionality let me know I will use that.

**Comment by jorge9200** [comment]
You can use start.js, to do it you have to:

1 - Add a start script to you info.json
![image](https://user-images.githubusercontent.com/8724844/34935444-375be98a-f9de-11e7-920d-48b3bc212b62.png)

2 - Implement start.js script

It is a normal script but it is launched just when you click on app icon, right before html loads. There you can listAccounts() and only when you have your answer (show login / show calendar) use the method start() which returns control to script.js and loads the html

**Comment by jorge9200** [comment]
Here it is gmail (other integrations) start.js script, just to show you how they are doing it

![image](https://user-images.githubusercontent.com/8724844/34935618-c5c17aaa-f9de-11e7-9bda-368f1f7fb48b.png)

**Comment by umair-brainx** [comment]
Wait. so when I will call start method from start.js it will always return control to the default View of the app i.e Login Or Is there any way where I can decide to which view open next?

**Comment by jorge9200** [comment]
It always return to default view, but you can (for example) add a class to the app view
`$(this).addClass('mode-login')` or `$(this).addClass('mode-calendar')` 
and then in your script.js launch the view you want as you are doing. 

The only change with this is that during async call (listAccounts) html is not loaded

**Comment by umair-brainx** [comment]
Fixed. Kindly have a look now.

**Comment by jorge9200** [comment]
fix!
