### ISSUE TITLE
Time and event is not showing right

### ISSUE THREAD

**Issue by jorge9200** [Inevio/GoogleCalendar#8]
Implementation:
![image](https://user-images.githubusercontent.com/8724844/34490317-cb854c4a-efdf-11e7-8bcf-afed327f6e90.png)

Design propossed:
![image](https://user-images.githubusercontent.com/8724844/34490337-d980381e-efdf-11e7-9801-cfe7551faa02.png)

**Comment by umair-brainx** [comment]
I will look into this

**Comment by umair-brainx** [comment]
I am following your this design
![screen shot 2018-01-15 at 12 49 42 pm](https://user-images.githubusercontent.com/26704318/34931925-bddd27b2-f9f2-11e7-86ef-d0de0dc978d6.png)

that is consistent to day view and week view. Although previously there was border-radius, I have removed that and added the default border according to design.

**Comment by jorge9200** [comment]
This is our design provided:

![image](https://user-images.githubusercontent.com/8724844/34934835-2b94626e-f9dc-11e7-890b-cb2a2917561c.png)

As you can see there is a diferent design for "all day events" and "timed events"

This is your design:

![image](https://user-images.githubusercontent.com/8724844/34934890-53fb891c-f9dc-11e7-9e6b-064889f66e5e.png)


Same design for "timed events" and "all day events"

**Comment by umair-brainx** [comment]
I have made the all day event and timed event design different i.e according to your design for month view. Kindly have a look.

**Comment by jorge9200** [comment]
seems right
